name: Bug Report
description: Report a bug or issue
title: "[Bug]: "
labels: ["bug"]

body:
  - type: input
    id: provider
    attributes:
      label: Provider (if applicable)
      placeholder: "anthropic, openai, google, etc."
    validations:
      required: false

  - type: input
    id: model
    attributes:
      label: Model (if applicable)
      placeholder: "claude-3-5-sonnet-20241022"
    validations:
      required: false

  - type: textarea
    id: bug_description
    attributes:
      label: Bug Description
      description: What's broken?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Code
      placeholder: |
        ```elixir
        {:ok, response} = ReqLLM.generate_text("provider:model", "prompt")
        ```
      render: elixir
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      placeholder: |
        - ReqLLM: 1.0.0-rc.5
        - Elixir: 1.17.0
        - OTP: 27
    validations:
      required: true
