name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]

body:
  - type: dropdown
    id: feature_type
    attributes:
      label: Feature Type
      options:
        - New provider
        - Provider feature extension
        - Core library enhancement
        - Documentation
        - Other
    validations:
      required: true

  - type: input
    id: provider
    attributes:
      label: Provider (if applicable)
      placeholder: "anthropic, openai, ollama, etc."
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What feature do you want and why?
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Example Usage
      placeholder: |
        ```elixir
        {:ok, response} = ReqLLM.your_feature(...)
        ```
    validations:
      required: false

  - type: dropdown
    id: contribution
    attributes:
      label: Can you contribute this?
      options:
        - "Yes, I can submit a PR"
        - "Yes, with guidance"
        - "No"
    validations:
      required: true
